//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAluno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplinas
    {
        public int DISID { get; set; }
        public string DISDESCRIACAO { get; set; }
        public string DISCH { get; set; }
        public int CURSOID { get; set; }
    
        public virtual Cursos Cursos { get; set; }
    }
}
