//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int MODID { get; set; }
        public string MODDESCRICAO { get; set; }
        public int MODANO { get; set; }
        public Nullable<int> VEID { get; set; }
    
        public virtual Veiculo Veiculo { get; set; }
    }
}
